---
kind: pipeline
type: docker
name: build and deploy site

steps:
  - name: build
    image: node:15
    commands:
      - npm install
      - npm run build
  - name: deploy
    image: node:15
    commands:
      - cd extension
      - npm install -g netlify-cli
      - netlify deploy --dir=dist
    environment:
      NETLIFY_AUTH_TOKEN:
        from_secret: NETLIFY_PAT
      NETLIFY_SITE_ID:
        from_secret: NETLIFY_APP_ID

trigger:
  ref:
    - refs/heads/master
